### ISSUE TITLE
when i use nv-pytorch22.09, but i can't get eval_acc to 0.72

### ISSUE THREAD

**Issue by BiduCui** [mlcommons/training_results_v2.1#6]
if anyone found, when use nv-pytorch 22.09 run bert, use the same datasets, model, LR,etc...，but can't get eval_acc to 0.72

**Comment by arjunsuresh** [comment]
What acc value are you able to achieve? How many GPUs did you use?

**Comment by BiduCui** [comment]
eval acc can achieve 0.63 when i use 64 Gpus

________________________________
发件人: Arjun Suresh ***@***.***>
发送时间: 2023年6月16日 5:15:23
收件人: mlcommons/training_results_v2.1
抄送: Cui,Zhigang; Author
主题: Re: [mlcommons/training_results_v2.1] when i use nv-pytorch22.09, but i can't get eval_acc to 0.72 (Issue #6)


What acc value are you able to achieve? How many GPUs did you use?

―

**Comment by arjunsuresh** [comment]
I think [this issue](https://github.com/mlcommons/training_results_v2.1/issues/10) is related.

**Comment by BiduCui** [comment]
tks，arjunsuresh!

**Comment by BiduCui** [comment]
problem was solved
